// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2rNvw6gewXMI9XijZvv48o1DRDEUewPg',
    appId: '1:372638829716:web:6e49a3410fd7c411eaf881',
    messagingSenderId: '372638829716',
    projectId: 'e-commerce--flutter',
    authDomain: 'e-commerce--flutter.firebaseapp.com',
    storageBucket: 'e-commerce--flutter.appspot.com',
    measurementId: 'G-CVQLJ33GB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaIx5Y3oFHKp1gXvOabv9kAqnXan2mqEo',
    appId: '1:372638829716:android:2bf9bb68990396deeaf881',
    messagingSenderId: '372638829716',
    projectId: 'e-commerce--flutter',
    storageBucket: 'e-commerce--flutter.appspot.com',
  );
}
